import type { ChecklistItem } from '@/types'

export const DEFAULT_CHECKLIST: ChecklistItem[] = [
  // THIS WEEK
  {
    id: 'ci-oregano-thyme',
    label: 'Start oregano & thyme indoors',
    detail: 'Plant in small cups/cells. Keep moist, warm. Takes 7-14 days to germinate.',
    timing: 'this-week',
    location: 'Indoors (cups)',
    completed: false,
  },
  {
    id: 'ci-basil',
    label: 'Start basil (Genovese) indoors',
    detail: 'Start in cups indoors OR wait 2-3 weeks and direct sow outside. Prefers warmth.',
    timing: 'this-week',
    location: 'Indoors or Hanging Pots',
    completed: false,
  },
  {
    id: 'ci-beets',
    label: 'Direct sow beets to Bed 1',
    detail: 'Sow Detroit Dark Red & Ruby Queen. Row 1 (left side of bed). 1" deep, 3" apart — thin to 4".',
    timing: 'this-week',
    location: 'Bed 1 – Row 1',
    completed: false,
  },
  {
    id: 'ci-arugula',
    label: 'Direct sow arugula (Rocket) to Bed 1',
    detail: 'Row 2. Surface sow, lightly cover. Germinates in 7-10 days. Succession plant every 2 weeks.',
    timing: 'this-week',
    location: 'Bed 1 – Row 2',
    completed: false,
  },
  {
    id: 'ci-cilantro',
    label: 'Direct sow cilantro to Bed 1',
    detail: 'Row 3 (right side). ¼" deep, 6" apart. Prefers cooler weather — sow now.',
    timing: 'this-week',
    location: 'Bed 1 – Row 3',
    completed: false,
  },
  {
    id: 'ci-carrots',
    label: 'Direct sow carrots to Bed 1',
    detail: 'Row 4 (bottom). ¼" deep, very thin row. Thin seedlings to 2-3" apart. Slow to germinate (10-21 days).',
    timing: 'this-week',
    location: 'Bed 1 – Row 4',
    completed: false,
  },
  // APRIL 15+
  {
    id: 'ci-lettuce',
    label: 'Direct sow Black Seeded Simpson lettuce',
    detail: 'Direct sow or transplant to hanging pots. Bolt-resistant, great for hanging baskets.',
    timing: 'april-15-plus',
    location: 'Hanging Pots',
    completed: false,
  },
  {
    id: 'ci-beans',
    label: 'Direct sow stringless beans to Bed 2',
    detail: 'After April 15. Row 1 (left side). 1" deep, 4" apart — no thinning needed.',
    timing: 'april-15-plus',
    location: 'Bed 2 – Row 1',
    completed: false,
  },
  {
    id: 'ci-cucumber',
    label: 'Direct sow cucumbers (Straight Eight) to Bed 2',
    detail: 'After April 15. Row 2 (center). 1" deep, 12" apart. May need trellis along bed edge.',
    timing: 'april-15-plus',
    location: 'Bed 2 – Row 2',
    completed: false,
  },
  {
    id: 'ci-squash',
    label: 'Direct sow summer squash (Butterstick) to Bed 2',
    detail: 'After April 15. Row 3 (right side). 1" deep, 18-24" apart. Sprawls — give space.',
    timing: 'april-15-plus',
    location: 'Bed 2 – Row 3',
    completed: false,
  },
  {
    id: 'ci-tomato-transplant',
    label: 'Transplant tomato starters to containers',
    detail: 'After April 15. 1 per 18-24" container pot. Along fence. Harden off first (7 days outdoors).',
    timing: 'april-15-plus',
    location: 'Container Pots 1-2',
    completed: false,
  },
  {
    id: 'ci-pepper-transplant',
    label: 'Transplant pepper starters to containers',
    detail: 'After April 15. 1-2 per container pot. Next to tomatoes along fence.',
    timing: 'april-15-plus',
    location: 'Container Pots 3-4',
    completed: false,
  },
  // BUY
  {
    id: 'ci-buy-strawberry',
    label: 'Buy strawberry crowns/starters',
    detail: 'Purchase bare-root crowns or potted starters. Plant around gazebo edges or in hanging baskets.',
    timing: 'buy',
    location: 'Gazebo area',
    completed: false,
  },
  {
    id: 'ci-buy-tomato',
    label: 'Buy tomato starters (if not starting from seed)',
    detail: 'Choose a determinate variety for containers (e.g. Celebrity, Bush Early Girl). 1 per pot.',
    timing: 'buy',
    location: 'Nursery',
    completed: false,
  },
  {
    id: 'ci-buy-pepper',
    label: 'Buy pepper starters',
    detail: 'Bell or Italian frying peppers work great in containers. Buy seedlings from nursery.',
    timing: 'buy',
    location: 'Nursery',
    completed: false,
  },
]
